title: Pliavi
email: pliavi.contato@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pliavi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pliavi
github_username:  pliavi
site.github.url: http://pliavi.github.io/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
